In [180]:
import numpy as np
import pandas as pd

In [181]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [182]:
movies.head(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [183]:
credits.head(5)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [184]:
movies=movies.merge(credits,on='title')

In [185]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [186]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [187]:

movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [188]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [189]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [190]:
movies.dropna(inplace=True)

In [191]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [192]:
movies.duplicated().sum()

np.int64(0)

In [193]:
movies.iloc[5].genres

'[{"id": 14, "name": "Fantasy"}, {"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}]'

In [194]:
import ast
def filter_name(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [195]:
movies['genres']=movies['genres'].apply(filter_name)

In [196]:
movies['keywords']=movies['keywords'].apply(filter_name)

In [197]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [198]:
import ast
def filter5_name(obj):
    l=[]
    ct=0;
    for i in ast.literal_eval(obj):
        if ct!=5:
            l.append(i['name'])
            ct+=1
        else:
            break
    return l

In [199]:
movies['cast']=movies['cast'].apply(filter5_name)

In [200]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [201]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [202]:
def filter_director(obj):
    l=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            l.append(i['name'])
            break
    return l

In [203]:
movies['crew']=movies['crew'].apply(filter_director)

In [204]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]

In [205]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [206]:
movies['overview']=movies['overview'].apply(lambda x: x.split())

In [207]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [208]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace("  ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace("  ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [209]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [210]:
movies['tag']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew,tag
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."

In [211]:
new_data=movies[['movie_id','title','tag']]
new_data

,movie_id,title,tag
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [212]:
new_data['tag']=new_data['tag'].apply(lambda x:" ".join(x))
new_data

C:\Users\Admin\AppData\Local\Temp\ipykernel_13712\2469885852.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['tag']=new_data['tag'].apply(lambda x:" ".join(x))

,movie_id,title,tag
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [213]:
new_data['tag'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science Fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez JamesCameron'

In [214]:
new_data['tag']=new_data['tag'].apply(lambda x:x.lower())
new_data

C:\Users\Admin\AppData\Local\Temp\ipykernel_13712\960479259.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['tag']=new_data['tag'].apply(lambda x:x.lower())

,movie_id,title,tag
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,ever since the second grade when he first saw ...

In [215]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [216]:
vectors=cv.fit_transform(new_data['tag']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [217]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [218]:
feature=cv.get_feature_names_out()
print(feature[:600:])

['000' '007' '10' '100' '11' '12' '13' '14' '15' '16' '17' '17th' '18'
 '18th' '19' '1930s' '1940s' '1950s' '1960s' '1970s' '1980' '1980s' '1985'
 '1990s' '19th' '20' '200' '2009' '20th' '21st' '24' '25' '30' '300' '3d'
 '40' '50' '500' '51' '60' '60s' '70' 'aaron' 'aaroneckhart' 'aarontaylor'
 'abandoned' 'abducted' 'abigailbreslin' 'abilities' 'ability' 'able'
 'aboard' 'abroad' 'abuse' 'abusive' 'academy' 'accent' 'accept'
 'accepted' 'accepts' 'access' 'accident' 'accidental' 'accidentally'
 'accompanied' 'accomplish' 'account' 'accountant' 'accused' 'ace'
 'achieve' 'act' 'acting' 'action' 'actions' 'activist' 'activities'
 'activity' 'actor' 'actors' 'actress' 'acts' 'actual' 'actually' 'adam'
 'adambrody' 'adams' 'adamsandler' 'adamscott' 'adamshankman' 'adaptation'
 'adapted' 'addict' 'addicted' 'addiction' 'adolescence' 'adopted'
 'adoption' 'adopts' 'adrienbrody' 'adult' 'adultery' 'adulthood' 'adults'
 'advantage' 'adventure' 'adventures' 'advertising' 'advice' 'affair'
 'affairs' 'affection' 'affections' 'afghanistan' 'africa' 'african'
 'aftercreditsstinger' 'afterlife' 'aftermath' 'age' 'aged' 'agency'
 'agenda' 'agent' 'agents' 'ages' 'aggression' 'aggressive' 'aging' 'ago'
 'agree' 'agrees' 'ahead' 'aid' 'aidanquinn' 'aided' 'aids' 'ailing' 'air'
 'aircraft' 'airplane' 'airport' 'aka' 'al' 'alabama' 'alan' 'alanalda'
 'alanarkin' 'alanrickman' 'alaska' 'albert' 'albertbrooks' 'alcohol'
 'alcoholic' 'alcoholism' 'alecbaldwin' 'alex' 'alexkendrick'
 'alfredhitchcock' 'alfredmolina' 'alfrewoodard' 'ali' 'alice' 'alien'
 'aliens' 'alike' 'alive' 'allen' 'alliance' 'allied' 'allies'
 'allisonjanney' 'allow' 'allows' 'ally' 'alongside' 'alpacino' 'alter'
 'alternate' 'alternative' 'alzheimer' 'amanda' 'amandapeet'
 'amandaseyfried' 'amateur' 'amazing' 'amazon' 'ambassador' 'ambition'
 'ambitious' 'ambulance' 'ambush' 'america' 'american' 'americans' 'amid'
 'amidst' 'amnesia' 'amp' 'amsterdam' 'amusement' 'amy' 'amyadams'
 'amysmart' 'analyst' 'anarchic' 'ancient' 'anderson' 'andiemacdowell'
 'andrew' 'android' 'andy' 'andygarcía' 'andyserkis' 'angel'
 'angelabassett' 'angeles' 'angelinajolie' 'angels' 'anger' 'anglee'
 'angry' 'angst' 'animal' 'animals' 'animated' 'animation'
 'anjelicahuston' 'anna' 'annafaris' 'annakendrick' 'annapaquin'
 'annasophiarobb' 'anne' 'annehathaway' 'anneheche' 'annemoss'
 'annettebening' 'annie' 'anniversary' 'annual' 'anonymous' 'answer'
 'answers' 'ant' 'anthology' 'anthony' 'anthonyanderson' 'anthonyhopkins'
 'anthonymackie' 'anthropomorphism' 'anti' 'antics' 'antoinefuqua'
 'antoniobanderas' 'antonyelchin' 'apart' 'apartheid' 'apartment' 'ape'
 'apes' 'apocalypse' 'apocalyptic' 'apparent' 'apparently' 'appear'
 'appears' 'apple' 'appointed' 'apprentice' 'approach' 'approaches'
 'approaching' 'april' 'arab' 'arch' 'archaeologist' 'architect' 'arctic'
 'area' 'aren' 'arena' 'argument' 'arise' 'aristocrat' 'arm' 'armed'
 'armored' 'arms' 'army' 'arnold' 'arnoldschwarzenegger' 'arranged'
 'arrest' 'arrested' 'arrival' 'arrive' 'arrives' 'arriving' 'arrow' 'art'
 'arthur' 'article' 'artificial' 'artist' 'artists' 'arts' 'ashley'
 'ashleyjudd' 'ashtonkutcher' 'asia' 'asian' 'aside' 'ask' 'asked'
 'asking' 'asks' 'aspirations' 'aspiring' 'assassin' 'assassinate'
 'assassination' 'assassins' 'assault' 'assigned' 'assignment' 'assistant'
 'assumes' 'asteroid' 'astronaut' 'astronauts' 'asylum' 'athlete'
 'atlantic' 'atomic' 'attack' 'attacked' 'attacks' 'attempt' 'attempted'
 'attempting' 'attempts' 'attending' 'attends' 'attention' 'attitude'
 'attorney' 'attract' 'attracted' 'attraction' 'attractive' 'audience'
 'audition' 'august' 'aunt' 'austin' 'australia' 'australian' 'austria'
 'author' 'authorities' 'authority' 'autism' 'auto' 'autobiographical'
 'automobile' 'avenge' 'average' 'avoid' 'awaits' 'awakens' 'award' 'away'
 'awry' 'ax' 'axe' 'babe' 'baby' 'bachelor' 'backdrop' 'background'
 'backgrounds' 'bad' 'bag' 'bahamas' 'bail' 'balance' 'ball' 'ballet'
 'baltimore' 'band' 'bandits' 'bangkok' 'banished' 'bank' 'banker' 'bar'
 'barbrastreisand' 'barely' 'bargained' 'barn' 'barney' 'barrier' 'barry'
 'barrylevinson' 'barrypepper' 'bars' 'base' 'baseball' 'based' 'basement'
 'basketball' 'bat' 'bathroom' 'batman' 'battle' 'battlefield' 'battles'
 'battling' 'bay' 'beach' 'bear' 'bears' 'beast' 'beasts' 'beat' 'beating'
 'beautiful' 'beauty' 'becky' 'bed' 'bedroom' 'bee' 'beer' 'befriends'
 'began' 'begin' 'beginning' 'begins' 'behavior' 'beings' 'beliefs'
 'believe' 'believed' 'believes' 'believing' 'beloved' 'belt' 'ben'
 'benaffleck' 'beneath' 'benfoster' 'beniciodeltoro' 'benjamin'
 'benjaminbratt' 'benkingsley' 'bennett' 'benstiller' 'bent' 'berlin'
 'berniemac' 'best' 'bet' 'beth' 'betrayal' 'betrayed' 'bettemidler'
 'better' 'betty' 'beverly' 'bible' 'big' 'bigger' 'biggest' 'bike'
 'biker' 'bikini' 'billhader' 'billionaire' 'billmurray' 'billnighy'
 'billpaxton' 'billpullman' 'billy' 'billybobthornton' 'billyconnolly'
 'billycrudup' 'billycrystal' 'biography' 'biological' 'bird' 'birth'
 'birthday' 'bisexual' 'bishop' 'bit' 'bite' 'bitter' 'bizarre' 'black'
 'blackmail' 'blade' 'blame' 'blind' 'blindness' 'bliss' 'block' 'blonde'
 'blood' 'bloodthirsty' 'bloody' 'blow' 'blue' 'board' 'boarding' 'boat'
 'bob' 'bobby' 'bobbyfarrelly' 'bobhoskins' 'bodies' 'body' 'bodyguard'
 'bold' 'bollywood' 'bomb' 'bombing' 'bond' 'bonds' 'bone' 'bonniehunt'
 'booby' 'book' 'books' 'border' 'bored' 'boredom' 'boring' 'born' 'boss'
 'boston' 'botched' 'bound' 'boundaries' 'bounty' 'bowling' 'box' 'boxer'
 'boxing' 'boy' 'boyfriend' 'boys' 'braddourif' 'bradleycooper' 'bradpitt'
 'brain' 'brand' 'brave' 'bravery' 'brazil' 'brazilian' 'break'
 'breakdown' 'breaking' 'breaks' 'breast' 'breckinmeyer' 'brendanfraser'
 'brendangleeson' 'brent' 'brettratner' 'brian' 'briancox' 'briandepalma'
 'bride' 'bridge' 'brief' 'brielarson' 'brien' 'bright' 'brilliant'
 'bring' 'bringing' 'brings' 'brink' 'britain' 'british' 'brittanymurphy'
 'broadcast' 'broadway' 'broke' 'broken' 'broker' 'bronx' 'brooklyn'
 'brooks' 'brothel' 'brother' 'brothers' 'brought']

In [219]:
from nltk.stem.porter import PorterStemmer

In [220]:
ps=PorterStemmer()

In [221]:
def stem(text):
    y=[]

    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [222]:
print(stem('actions'))
print(stem('activities'))

action
activ

In [223]:
new_data['tag']=new_data['tag'].apply(stem)

C:\Users\Admin\AppData\Local\Temp\ipykernel_13712\3268543316.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['tag']=new_data['tag'].apply(stem)

In [224]:
vectors=cv.fit_transform(new_data['tag']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [225]:
feature=cv.get_feature_names_out()
print(feature[:600:])

['000' '007' '10' '100' '11' '12' '13' '14' '15' '16' '16th' '17' '17th'
 '18' '18th' '19' '1910' '1920' '1930' '1940' '1950' '1950s' '1960'
 '1960s' '1970' '1970s' '1971' '1974' '1980' '1985' '1990' '1999' '19th'
 '20' '200' '2001' '2003' '2009' '20th' '21st' '24' '25' '30' '300' '3d'
 '40' '50' '500' '51' '60' '70' 'aaron' 'aaroneckhart' 'aarontaylor'
 'abandon' 'abduct' 'abigailbreslin' 'abil' 'abl' 'aboard' 'aborigin'
 'abov' 'abroad' 'abus' 'academi' 'accent' 'accept' 'access' 'accid'
 'accident' 'acclaim' 'accompani' 'accomplish' 'account' 'accus' 'ace'
 'achiev' 'act' 'action' 'activ' 'activist' 'activities' 'actor' 'actress'
 'actual' 'ad' 'adam' 'adambrodi' 'adamsandl' 'adamscott' 'adamshankman'
 'adapt' 'add' 'addict' 'adjust' 'admir' 'admit' 'adolesc' 'adolf' 'adopt'
 'ador' 'adrienbrodi' 'adult' 'adulteri' 'adulthood' 'advanc' 'adventur'
 'adventure' 'advertis' 'advic' 'advis' 'affair' 'affect' 'afghanistan'
 'africa' 'african' 'aftercreditssting' 'afterlif' 'aftermath' 'ag' 'age'
 'agenc' 'agency' 'agenda' 'agent' 'agents' 'aggress' 'ago' 'agre' 'ahead'
 'aid' 'aidanquinn' 'ail' 'aim' 'air' 'aircraft' 'airplan' 'airport' 'aka'
 'al' 'alabama' 'alan' 'alanalda' 'alanarkin' 'alanrickman' 'alaska'
 'albert' 'albertbrook' 'alcatraz' 'alcohol' 'alecbaldwin' 'alex'
 'alexapenavega' 'alexisbledel' 'alexkendrick' 'alfredhitchcock'
 'alfredmolina' 'alfrewoodard' 'ali' 'alic' 'alice' 'alicebraga' 'alien'
 'alik' 'aliv' 'alive' 'allen' 'alli' 'allianc' 'allisonjanney' 'allow'
 'alon' 'alongsid' 'alpacino' 'alpha' 'alreadi' 'alter' 'altern' 'alway'
 'alyssa' 'alzheimer' 'amanda' 'amandapeet' 'amandaseyfri' 'amateur'
 'amaz' 'amazon' 'ambassador' 'amberheard' 'ambigu' 'ambit' 'ambiti'
 'ambul' 'ambush' 'america' 'american' 'amid' 'amidst' 'amnesia' 'amp'
 'amsterdam' 'amus' 'amy' 'amyadam' 'amysmart' 'analyst' 'anarch'
 'ancient' 'anderson' 'andi' 'andiemacdowel' 'andrew' 'android' 'andy'
 'andygarcía' 'andyserki' 'angel' 'angela' 'angelabassett' 'angeles'
 'angelinajoli' 'anger' 'angle' 'angri' 'angst' 'ani' 'anim' 'animals'
 'anjelicahuston' 'ann' 'anna' 'annabel' 'annafari' 'annakendrick'
 'annapaquin' 'annasophiarobb' 'anne' 'annehathaway' 'annehech' 'annemoss'
 'annetteben' 'anni' 'annie' 'anniversari' 'announc' 'annual' 'anonym'
 'anoth' 'answer' 'ant' 'antholog' 'anthoni' 'anthonyanderson'
 'anthonyhopkin' 'anthonymacki' 'anthropomorph' 'anti' 'antic' 'antiqu'
 'antoinefuqua' 'antoniobandera' 'antonyelchin' 'anyon' 'anyth' 'apart'
 'apartheid' 'apartment' 'ape' 'apocalyps' 'apocalypse' 'apocalypt'
 'appar' 'appear' 'appl' 'apple' 'appoint' 'appreci' 'apprentic'
 'approach' 'april' 'arab' 'arbitrari' 'arch' 'archaeologist' 'archeolog'
 'architect' 'arctic' 'area' 'aren' 'arena' 'argument' 'aris' 'aristocrat'
 'arm' 'armi' 'armor' 'army' 'arnold' 'arnoldschwarzenegg' 'arrang'
 'arrest' 'arriv' 'arrog' 'arrow' 'art' 'arthur' 'articl' 'artifact'
 'artifici' 'artist' 'ash' 'ashley' 'ashleyjudd' 'ashtonkutch' 'asia'
 'asian' 'asid' 'ask' 'aspir' 'assassin' 'assault' 'assign' 'assist'
 'assistant' 'associ' 'assum' 'asteroid' 'astronaut' 'asylum' 'atheist'
 'athlet' 'atlant' 'atom' 'attack' 'attacks' 'attempt' 'attend' 'attent'
 'attitud' 'attorney' 'attract' 'auction' 'audienc' 'audit' 'august'
 'aunt' 'austin' 'australia' 'australian' 'austria' 'author' 'autism'
 'auto' 'autobiograph' 'automobil' 'aveng' 'averag' 'avoid' 'await'
 'awaken' 'awar' 'award' 'away' 'awkward' 'awri' 'awry' 'ax' 'axe' 'babe'
 'babi' 'baby' 'bachelor' 'backdrop' 'background' 'backpack' 'bad' 'bag'
 'bahama' 'bail' 'bailey' 'balanc' 'ball' 'ballet' 'balloon' 'baltimor'
 'ban' 'band' 'bandit' 'bangkok' 'banish' 'bank' 'banker' 'bar'
 'barbarian' 'barbrastreisand' 'bare' 'bargain' 'barn' 'barney' 'baron'
 'barri' 'barrier' 'barrylevinson' 'barrypepp' 'barrysonnenfeld' 'bas'
 'base' 'basebal' 'basement' 'basketbal' 'basketball' 'bat' 'bath'
 'bathroom' 'batman' 'battl' 'battle' 'battlefield' 'bay' 'beach' 'beam'
 'bear' 'beast' 'beat' 'beauti' 'beautiful' 'beauty' 'becam' 'becaus'
 'becom' 'bed' 'bedroom' 'bee' 'beer' 'befor' 'befriend' 'began' 'begin'
 'begins' 'behavior' 'belgium' 'belief' 'believ' 'bell' 'bella' 'belong'
 'belov' 'belt' 'ben' 'benaffleck' 'bend' 'beneath' 'benefit' 'benfost'
 'beniciodeltoro' 'benjamin' 'benjaminbratt' 'benkingsley' 'bennett'
 'benstil' 'bent' 'berlin' 'berniemac' 'best' 'bet' 'beth' 'betray'
 'bettemidl' 'better' 'betti' 'beverli' 'bibl' 'biblic' 'bicycl' 'bid'
 'big' 'bigger' 'biggest' 'bike' 'biker' 'bikini' 'billhad' 'billi'
 'billionair' 'billmurray' 'billnighi' 'billpaxton' 'billpullman'
 'billybobthornton' 'billyconnolli' 'billycrudup' 'billycryst' 'biographi'
 'biolog' 'biologist' 'bird' 'birth' 'birthday' 'bisexu' 'bishop' 'bit'
 'bite' 'bitten' 'bitter' 'bizarr' 'black' 'blackmail' 'blade' 'blame'
 'blend' 'blind' 'bliss' 'block' 'blond' 'blood' 'bloodi' 'bloodthirsti'
 'blow' 'blue' 'board' 'boat' 'bob' 'bobbi' 'bobbyfarrelli' 'bobhoskin'
 'bodi' 'body' 'bodyguard' 'bold' 'bollywood' 'bomb' 'bomber' 'bond'
 'bone' 'bonniehunt' 'boobi' 'book' 'border' 'bore' 'boredom' 'born'
 'boss' 'boston' 'botch' 'bottl' 'bound' 'boundari' 'bounti' 'bowl' 'box'
 'boxer' 'boy' 'boyfriend' 'boys' 'braddourif' 'bradleycoop' 'bradpitt'
 'brain' 'brand' 'brave' 'braveri' 'brazil' 'brazilian' 'break'
 'breakdown' 'breast' 'breath' 'breckinmey' 'breed' 'brendanfras'
 'brendangleeson' 'brent' 'brettratn' 'brian' 'briancox' 'briandepalma'
 'brick' 'bride' 'bridesmaid' 'bridg' 'brief' 'brielarson' 'brien'
 'bright' 'brilliant' 'bring' 'brink' 'britain' 'british' 'brittanymurphi'
 'broadcast' 'broadway' 'broke' 'broken' 'broker' 'bronx' 'brook'
 'brooklyn' 'broom' 'brothel']

In [226]:
from sklearn.metrics.pairwise import cosine_similarity as cos_sim

In [227]:
similarity=cos_sim(vectors)
similarity[1]

array([0.06855912, 1.        , 0.04347826, ..., 0.04012862, 0.        ,
       0.02128141])

In [228]:
def recommend(movie):
    movie_ind=new_data[new_data['title']==movie].index[0]
    dist=similarity[movie_ind]
    movies_list=sorted(list(enumerate(dist)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_data.iloc[i[0]].title)

In [229]:
recommend('Batman Begins')

The Dark Knight
Batman
The Dark Knight Rises
Batman
Batman & Robin

In [230]:
import pickle

In [231]:
pickle.dump(new_data.to_dict(),open('movie_dict.pkl','wb'))

In [232]:
pickle.dump(similarity, open('similarity.pkl','wb'))